namespace JustTrack
{
    /// <summary>
    /// Represents an ad impression to be sent to the justtrack backend. This class is used to collect
    /// data related to ad impressions, which can be utilized to calculate the ad revenue generated by
    /// your app.
    /// </summary>
    public class AdImpression
    {
        /// <summary>
        /// Gets the ad unit identifier.
        /// </summary>
        internal string Unit { get; private set; }

        /// <summary>
        /// Gets the SDK name that provided this ad impression.
        /// </summary>
        internal string SdkName { get; private set; }

        /// <summary>
        /// Gets the ad network that provided this ad impression.
        /// </summary>
        internal string? Network { get; private set; } = null;

        /// <summary>
        /// Gets the placement identifier for this ad impression.
        /// </summary>
        internal string? Placement { get; private set; } = null;

        /// <summary>
        /// Gets the test group identifier for A/B testing purposes.
        /// </summary>
        internal string? TestGroup { get; private set; } = null;

        /// <summary>
        /// Gets the segment name for this ad impression.
        /// </summary>
        internal string? SegmentName { get; private set; } = null;

        /// <summary>
        /// Gets the instance name for this ad impression.
        /// </summary>
        internal string? InstanceName { get; private set; } = null;

        /// <summary>
        /// Gets the bundle ID of the advertised app.
        /// </summary>
        internal string? BundleId { get; private set; } = null;

        /// <summary>
        /// Gets the revenue amount generated by this ad impression.
        /// </summary>
        internal Money? Revenue { get; private set; } = null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AdImpression"/> class.
        /// </summary>
        /// <param name="pUnit">The ad unit identifier.</param>
        /// <param name="pSdkName">The name of the SDK that provided this ad impression.</param>
        public AdImpression(string pUnit, string pSdkName)
        {
            this.Unit = pUnit;
            this.SdkName = pSdkName;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AdImpression"/> class.
        /// </summary>
        /// <param name="pUnit">The ad unit type.</param>
        /// <param name="pSdkName">The name of the SDK that provided this ad impression.</param>
        public AdImpression(AdUnit pUnit, string pSdkName)
        {
            this.Unit = AdUnitInternalConversation.ToInternalString(pUnit);
            this.SdkName = pSdkName;
        }

        /// <summary>
        /// Sets the network for this ad impression.
        /// </summary>
        /// <param name="pNetwork">The name of the ad network which provided the ad. May be null.</param>
        /// <returns>This instance to allow for method chaining.</returns>
        public AdImpression SetNetwork(string? pNetwork)
        {
            this.Network = pNetwork;

            return this;
        }

        /// <summary>
        /// Sets the placement for this ad impression.
        /// </summary>
        /// <param name="pPlacement">The placement of the ad. May be null.</param>
        /// <returns>This instance to allow for method chaining.</returns>
        public AdImpression SetPlacement(string? pPlacement)
        {
            this.Placement = pPlacement;

            return this;
        }

        /// <summary>
        /// Sets the test group for this ad impression.
        /// </summary>
        /// <param name="pTestGroup">The test group of the user if we are A/B testing. May be null.</param>
        /// <returns>This instance to allow for method chaining.</returns>
        public AdImpression SetTestGroup(string? pTestGroup)
        {
            this.TestGroup = pTestGroup;

            return this;
        }

        /// <summary>
        /// Sets the segment name for this ad impression.
        /// </summary>
        /// <param name="pSegmentName">The name of the segment of the ad. May be null.</param>
        /// <returns>This instance to allow for method chaining.</returns>
        public AdImpression SetSegmentName(string? pSegmentName)
        {
            this.SegmentName = pSegmentName;

            return this;
        }

        /// <summary>
        /// Sets the instance name for this ad impression.
        /// </summary>
        /// <param name="pInstanceName">The name of the instance of the ad. May be null.</param>
        /// <returns>This instance to allow for method chaining.</returns>
        public AdImpression SetInstanceName(string? pInstanceName)
        {
            this.InstanceName = pInstanceName;

            return this;
        }

        /// <summary>
        /// Sets the bundle ID for this ad impression.
        /// </summary>
        /// <param name="pBundleId">The bundle ID of the advertised app. May be null.</param>
        /// <returns>This instance to allow for method chaining.</returns>
        public AdImpression SetBundleId(string? pBundleId)
        {
            this.BundleId = pBundleId;

            return this;
        }

        /// <summary>
        /// Sets the revenue for this ad impression.
        /// </summary>
        /// <param name="pRevenue">The amount of revenue this ad generated. May be zero but must not be negative.</param>
        /// <returns>This instance to allow for method chaining.</returns>
        public AdImpression SetRevenue(Money? pRevenue)
        {
            this.Revenue = pRevenue;

            return this;
        }
    }
}