// DO NOT EDIT, AUTOMATICALLY GENERATED BY updateCode.sh

namespace JustTrack
{
    /// <summary>
    /// Contains build configuration information for the justtrack SDK.
    /// </summary>
#pragma warning disable SA1401 // Fields should be private
    internal class BuildConfig
    {
#if UNITY_WEBGL
        /// <summary>
        /// Gets the version number of the justtrack SDK for WebGL platform.
        /// </summary>
        internal static string SdkVersionWebGl = "1.0.0";
#else
        /// <summary>
        /// Gets the version number of the justtrack SDK for native platforms (Android/iOS).
        /// </summary>
        internal static string SdkVersion = "7.1.0";
#endif
    }
#pragma warning restore SA1401
}
