// DO NOT EDIT, AUTOMATICALLY GENERATED BY updateCode.sh

namespace JustTrack
{
    /// <summary>
    /// Contains build configuration information for the justtrack SDK.
    /// </summary>
#pragma warning disable SA1401 // Fields should be private
    internal class BuildConfig
    {
        /// <summary>
        /// Gets the version number of the justtrack SDK.
        /// </summary>
        internal static string SdkVersion = "8.0.0";
    }
#pragma warning restore SA1401
}
