// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by tools/genAdapterVersions.js from tracking-sdk/sdk/deployment/version.properties

namespace JustTrack
{
    /// <summary>
    /// Contains version information for various SDK adapters.
    /// </summary>
    internal static class AdapterVersions
    {
        // Android adapter versions

        /// <summary>
        /// Version of the Android AppLovin adapter.
        /// </summary>
        public const string AndroidApplovin = "2.0.0";

        /// <summary>
        /// Version of the Android Firebase adapter.
        /// </summary>
        public const string AndroidFirebase = "1.0.1";

        /// <summary>
        /// Version of the Android IronSource adapter.
        /// </summary>
        public const string AndroidIronsource = "2.0.0";

        /// <summary>
        /// Version of the Android Unity Ads adapter.
        /// </summary>
        public const string AndroidUnityads = "1.0.1";

        // iOS adapter versions

        /// <summary>
        /// Version of the iOS AppLovin adapter.
        /// </summary>
        public const string IosApplovin = "1.0.0";

        /// <summary>
        /// Version of the iOS Firebase adapter.
        /// </summary>
        public const string IosFirebase = "1.0.0";

        /// <summary>
        /// Version of the iOS IronSource adapter.
        /// </summary>
        public const string IosIronsource = "1.0.0";

        /// <summary>
        /// Version of the iOS Unity Ads adapter.
        /// </summary>
        public const string IosUnityads = "1.0.0";

        /// <summary>
        /// Version of the iOS Google ODM adapter.
        /// </summary>
        public const string IosGoogleodm = "1.0.0";
    }
}
